# Generated by Django 5.1.4 on 2025-01-01 07:41

import django.core.validators
import django.db.models.deletion
import warranty_keeper.core.model_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('item_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('purchase_date', models.DateField()),
                ('period', models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (9, '9 Months'), (12, '12 Months'), (24, '24 Months'), (36, '36 Months')], default=24)),
                ('description', models.TextField(blank=True, null=True)),
                ('invoice_img', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('deleted', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
            ],
            options={
                'abstract': False,
            },
            bases=(warranty_keeper.core.model_mixins.SoftDeleteMixin, models.Model),
        ),
    ]
